services:
  - type: web
    name: cblue-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r services/api/requirements.txt
    startCommand: uvicorn services.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
